### ISSUE TITLE
Final Project Submission of Bryn McCarthy

### ISSUE THREAD

**Issue by bam2231** [QMSS-G5072-2020/final_project_mccarthy#1]
@SUN-Wenjun @lonadai0121 ffd5261

**Comment by lonadai0121** [comment]
4.5/5 very good project: presents wide-ranging functionality but lack of complexity; 
3/3 well commented and documented
3/3 The code is efficient, correct, and minimal
3/3 The package structure is clear, easy to follow, and closely matches the structure discussed in class.
3/3 The package, data, and functions’ documentation is clear and easy to follow.
3/3 The package installs without problems.
3/3 The package contains automated testing of at least some of the main functions and these tests run without errors.
Bonus 1/2 Public website but poorly explained, no function descriptions
